project/accounts/urls.py
from django.urls import path
from .views import user_register, user_login, user_logout

app_name='accounts'
urlpatterns = [
    path('register/', user_register, name = 'user_register'),
    path('login/', user_login, name = 'login'),
    path('logout/', user_logout ,name = 'logout'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/', include('accounts.urls')),

]

project/myapp/urls.py
from django.urls import path
from .views import (
    home, 
    detail, 
    delete, 
    create,
    update,
)

app_name='myapp'
urlpatterns = [
    path('', home, name="home"),
    path('detail/<int:todo_id>/', detail, name="detail"),
    path('delete/<int:todo_id>/', delete, name="delete"),
    path('update/<int:todo_id>/', update, name="update"),
    path('create/', create, name="create"),
]

project/urls.py
from django.urls import path
from 

urlpatterns = [
    path('register', user_register, name = 'user_register')
]

project/accounts/models.py
from django.db import models

# Create your models here.

project/myapp/models.py
from django.db import models
# from django.urls import reverse

class Todo(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
    # def get_absolute_url(self):
    #     return reverse("myapp:detail")

project/accounts/forms.py
from django import forms


class UserRegistrationForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

project/myapp/forms.py
from django import forms
from .models import Todo

class TodoCreateForm(forms.Form):
    title = forms.CharField()
    body = forms.CharField()
    created = forms.DateTimeField()
    status=forms.BooleanField()


class TodoUpdateForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = '__all__'

project/accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import UserRegistrationForm, UserLoginForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(cd['username'], cd['email'], cd['password'])
            user.first_name = cd['first_name']
            user.last_name = cd['last_name']
            user.save()
            messages.success(request, 'User Registered Successfully!', 'success')
            return redirect('myapp:home')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form':form})



def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'Logged in Successfully!', 'success')
                return redirect('myapp:home')
            else:
                messages.error(request, 'username or password is wrong!', 'danger')
    else:
        form = UserLoginForm()
    
    return render(request, 'registration/login.html', {'form':form})




def user_logout(request):
    logout(request)
    messages.success(request, 'logged out successfully!', 'success')
    return redirect('myapp:home')

project/myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Todo
from django.contrib import messages
from .forms import TodoCreateForm, TodoUpdateForm

def home(request):
    context={
        "todos": Todo.objects.filter(status=True)
    }
    return render(request, "myapp/home.html",context)

# def home2(request):
#     # person = {'name':'Amin', 'lastname':'Hezarkhani'}
#     return render(request, "myapp/home2.html", {'name':'amin', 'lastname':'hezarkhani', 'value':2, 'p':'Django!'})

def detail(request, todo_id):
    context = {
        "todo": get_object_or_404(Todo, id=todo_id, status=True)

    }
    return render(request, "myapp/detail.html", context)


def delete(request, todo_id):
    Todo.objects.get(id=todo_id).delete()
    messages.success(request, 'Your todo was successfully deleted!', 'success')
    return redirect("myapp:home")


def create(request):
    if request.method == 'POST':
        form = TodoCreateForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Todo.objects.create(title=cd['title'], body=cd['body'], created=cd['created'], status=cd['status'])
            messages.success(request, 'Your Todo created successfully!', 'success')
            return redirect('myapp:home')
    else:
       form = TodoCreateForm()
    return render (request, 'myapp/create.html', {'form':form})


#این جا خیلی مهم و یه مقدار پیچیده هستش و برای جلسه ۱۹ هستش
def update(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    if request.method == 'POST':
        form = TodoUpdateForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Todo updated successfully!', 'success')
            return redirect('myapp:detail', todo_id)
    else:
        form = TodoUpdateForm(instance=todo)
    return render(request, 'myapp/update.html', {'form':form})

project/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <style>
        .jumbotron{
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>
</head>
<body>
    <!-- در واقع اومدیم یه فایل ساختیم به نام نوبار با فرمت اچ تی ام ال و کد نوبار رو کات کردیم اونجا و اینجا اینکلود کردیم که داخل بیس شلوغ نشه -->
    {% include 'myapp/navbar.html' %}
    <div class="jumbotron">
        {% include 'myapp/messages.html' %}
        {% block content %}{% endblock %}
    </div>
</body>
</html>

project/templates/myapp/create.html
{% extends 'myapp/base.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h3>Create Todo</h3>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="create">
        </form>
    {% else %}
        <div class="alert alert-danger">You Are not login!</div>
    {% endif %}
{% endblock %}

project/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}  {{todo.title}} {% endblock %}
{% block content %}
    <a href="{% url 'myapp:delete' todo.id %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'myapp:update' todo.id %}" class="btn btn-info">Update</a>
    <h3>{{todo.title}}</h3>
    <p>Author: {{user.get_full_name}}</p>
    <h5>{{todo.created}}</h5>
    <p>{{todo.body}}</p>
{% endblock %}

project/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% block title %}Home1{% endblock %}
{% block content %}
    {% if request.user.is_authenticated %}
        <div class="card">
                {% for todo in todos %}
                    <a class="card-body" href="{% url 'myapp:detail' todo.id %}">{{todo.title}}</a>
                {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-danger">You Are not login!</div>
    {% endif %}
{% endblock %}

project/templates/myapp/messages.html
<!-- میگه ببین پیغامی وجود داره یا نه، اگه وجود داشت بیا حلقه فور بزن و پیغام رو نشون بده بعد پاک کردن پست -->
{% if messages %}

    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{ msg }}</p>
    {% endfor %}

{% endif %}

project/templates/myapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'myapp:home' %}">Home</a>
      <a class="navbar-brand" href="{% url 'myapp:create' %}">Create</a>
      <a class="navbar-brand" href="{% url 'accounts:user_register' %}">Register</a>
      <a class="navbar-brand" style="margin-right:1000px" href="{% url 'accounts:login' %}">Login</a>
    </div>
  </nav>

project/templates/myapp/update.html
{% extends 'myapp/base.html' %}

{% block content %}
    <h3>Update Todo</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Create">
    </form>
{% endblock %}